version: "3.7"

services: 
    tf_serving:
        build: ./app/image_classifier/model/
        ports:
            - 8500:8500
            - 8501:8501
        volumes:
            - ./app/image_classifier/model/export:/models/model
    web:
        build: ./app
        command: python manage.py flush --no-input
        command: python manage.py migrate --no-input 
        command: python manage.py runserver 0.0.0.0:8000
        volumes: 
            - ./app/:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./.dev.env
        stdin_open: true # docker run -i
        tty: true        # docker run -t
